#! /bin/sh

# 
# This script generates an ansible inventory file.  The system to be managed is within a secure environment and is accessed 
# using a connection from a jumpbox (or bastion host).  The jumpbox has a publically accessible IP address.  Ansible uses ssh
# to connect to the managed host.  The inventory file generated by this script identifies the jumpbox (jumpbox_public) and the
# system to be managed (webserver_private).  Their respective IP addresses, which are known at runtime, are filled into the 
# template below.  The ssh command is the standard ssh command used to connect to a system via a proxy which in this case is 
# the jumpbox.
# 

fip="${1}"
webserver="${2}"

# create an ansible inventory file and fill in the ip addresses for the jump box and vsi
#
{
echo "[jumpbox_public]"
echo "my-public-bastion ansible_host=${fip}"
echo " "

echo "[webserver_private]"
echo "my-webserver-target ansible_host=${webserver}"
echo " "

echo "[webserver_private:vars]"
echo "ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand=\"ssh -W %h:%p -q root@${fip} -o StrictHostKeyChecking=no -o IdentityFile=./keyfile \"'"
echo " "

echo "[all:vars]"
echo "ansible_ssh_private_key_file=./keyfile "
echo " "
} > inventory.ini
38 changes: 38 additions & 0 deletions 