 - name: Playbook to install Apache
   hosts: webserver_private
   remote_user: root
   
   tasks:
    - name: Ansible apt install apache2
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true