#
#  A playbook that will create an inventory and then execute ansible against the inventory
#  to install an application.
#
#  Tasks in Ansible are ran in the order of their definition within the playbook so these
#  tasks will run as needed in this order.
#
- hosts: localhost
  connection: local
  

  tasks:
    - name: Prints a debug message
      ansible.builtin.debug:
        msg:
        - "This playbook is at the extension level scripts directory"

    - name: Print environment vars
      ansible.builtin.command: env
      register: dump_env_vars
    - debug: var=dump_env_vars.stdout_lines

    - name: Print current directory name
      ansible.builtin.command: pwd
      register: directory_name
    - debug: var=directory_name.stdout_lines 

    - name: List current directory contents
      ansible.builtin.command: ls -lgart
      register: directory_list
    - debug: var=directory_list.stdout_lines

    - name: List playbook directory contents
      ansible.builtin.command: ls -lgart ../playbook
      register: playbook_directory_list
    - debug: var=playbook_directory_list.stdout_lines

    - name: generate inventory and keyfile
      command: ../playbook/generate-inventory.sh "{{ fp_vsi_floating_ip_address }}" "{{ webserver_ip_address }}" "{{ ssh_private_key }}"
      register: generate_result
      ignore_errors: True
    - debug: var=generate_result.stdout_lines  

    - name: show the contents of the inventory file
      command: cat inventory-test.txt
      register: inventory_contents
    - debug: var=inventory_contents.stdout_lines

    - name: show the contents of the keyfile
      command: cat keyfile
      register: keyfile_contents
    - debug: var=keyfile_contents.stdout_lines  

    - name: List current directory contents
      ansible.builtin.command: ls -lgart
      register: directory_list_new
    - debug: var=directory_list_new.stdout_lines    

    # run ansible using the inventory file created and install apache
    - name: install apache 
      command: ansible-playbook -i inventory-test.txt ../playbook/install-apache-on-webservers.yaml --check
      register: playbook_out

    # this is to get output from the ansible operation that installed the apache app.
    - debug: var=playbook_out
