#
#  A playbook that will create an inventory and then execute ansible against the inventory
#  to install an application.
#
#  Tasks in Ansible are ran in the order of their definition within the playbook so these
#  tasks will run as needed in this order.
#
- hosts: localhost
  connection: local
  

  tasks:
    - name: generate inventory file
      command: ../playbook/generate-inventory.sh "{{ fp_vsi_floating_ip_address }}" "{{ webserver_ip_address }}"
      register: generate_result
      ignore_errors: True
    - debug: var=generate_result.stdout_lines  

    - name: show the contents of the inventory file
      command: cat inventory.ini
      register: inventory_contents
    - debug: var=inventory_contents.stdout_lines

    - name: generate ssh key file
      command: ../playbook/generate-keyfile.sh "{{ ssh_private_key }}"
      register: keyfile_result
      ignore_errors: True
    - debug: var=keyfile_result.stdout_lines     

    # run ansible using the inventory file created and install apache
    - name: install apache 
      command: ansible-playbook -i inventory.ini ../playbook/install-apache-on-webservers.yaml
      register: playbook_out

    # this is to get output from the ansible operation that installed the apache app.
    - debug: var=playbook_out
