- name: Hello world ansible pre validate playbook
  hosts: localhost
  vars:
    ibmcloud_api_key: "{{ lookup('ansible.builtin.env', 'ibmcloud_api_key')}}"
  tasks:
    - name: API key is NOT defined
      debug:
        msg: "*** ibmcloud_api_key NOT defined"
      when: (ibmcloud_api_key is undefined) or (ibmcloud_api_key | length == 0)

    - name: Pre Validate Ansible Environment
      debug:
        msg:
          - "  ENV:"
          - "*****************************************"
          - "{{ansible_env}}"
          - "  FACTS:"
          - "*****************************************"
          -  "{{ansible_facts}}"