
- name: Validate pre playbook
  hosts: localhost
  vars:
    ibmcloud_api_key: "{{ lookup('ansible.builtin.env', 'ibmcloud_api_key')}}"
  tasks:
   - name: Print result
     ansible.builtin.debug:
       msg: "Received api key" 
     when: ibmcloud_api_key is defined 
